server.port=8085
spring.application.name=notification-service

# Eureka configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Email configuration (Sử dụng Mailtrap để Test giao diện - AN TOÀN & ĐẸP)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=cd5394292feffa
spring.mail.password=92517ba3324c8f
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
